# Generated by Django 3.2.9 on 2021-11-08 11:00

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='image',
            field=models.ImageField(upload_to=bills.models.upload_to, verbose_name='image'),
        ),
    ]
