# Generated by Django 3.2.9 on 2021-11-09 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20211108_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payedbill',
            name='sumbited_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
