# Generated by Django 3.2.9 on 2021-11-07 17:10

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=200)),
                ('bill_icon', models.ImageField(upload_to=dashboard.models.upload_to, verbose_name='bill_icon_image')),
            ],
            options={
                'ordering': ('-bill_name',),
            },
        ),
    ]
